# This is a basic workflow to help you get started with Actions

name: Pack and Publish

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
          
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          
      - name: Echo Github_Ref
        run: echo "::debug::${{ GITHUB_REF }}"
          
      - name: Set new Version
        uses: BlobDevelopment/copy-and-replace-tokens@v1
        with:
         source: 'library.json.template'
         target: 'library.json'
        env:
          VERSION: ${{ GITHUB_REF }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: library.json # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: library.json
      
      - name: Pack Package
        run: pio package pack -o ${{ github.workspace }}/FastEsp8266ShiftRegister.tar.gz
        
      - name: Upload Pack to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/FastEsp8266ShiftRegister.tar.gz
          tag: $GITHUB_REF
          
      - name: Publish Package
        run: pio package publish --owner nilsauf --notify
